template = "../templates/basic-label.svg"

[text.main]
# Plain text is filament 1, braces are 2, and brackets are 3.
content = 'M{3}x[10]'

[[icons.fasteners]]
icon = "../icons/bolt.svg"

[[icons.fasteners]]
spacer = "1mm"

[[icons.fasteners]]
icon = "../icons/nut.svg"
