template = "basic-label.svg"

[text.main]
# Plain text is filament 0, braces are 1, and brackets are 2.
content = 'M{3}x[10]'

[[icons.fasteners]]
icon = "icons/bolt.svg"

[[icons.fasteners]]
spacer = "1mm"

[[icons.fasteners]]
icon = "icons/nut.svg"
